name: arl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.13
  - cudatoolkit=11.3
  - cycler=0.11.0
  - debugpy=1.5.1
  - ffmpeg=4.3
  - imageio=2.26
  - matplotlib-base=3.7.1
  - pillow=9.4
  - pip=21.1.3
  - psutil=5.9
  - python=3.8
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pyzmq=23.2.0
  - scikit-image=0.18.1
  - scipy=1.10.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - zeromq=4.3.4
  - pip:
    - dm-control==1.0.9
    - dm-env==1.5
    - dm-robotics-agentflow==0.5.0
    - dm-robotics-controllers==0.5.0
    - dm-robotics-geometry==0.5.0
    - dm-robotics-moma==0.5.0
    - dm-robotics-transformations==0.5.0
    - dm-tree==0.1.6
    - functorch==0.2.1
    - future==0.18.3
    - greenlet==2.0.2
    - grpcio==1.44.0
    - gym==0.23.1
    - gym-notices==0.0.4
    - h5py==3.8.0
    - hydra-core==1.1.0
    - msgpack==1.0.5
    - mujoco==2.3.1
    - mujoco-py==2.1.2
    - numpy==1.22.2
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - opencv-python==4.5.3
    - pandas==1.3.0
    - protobuf==3.19.4
    - pybullet==3.2.0
    - pydot==1.4.2
    - pygame==2.1.2
    - rsa==4.8
    - scikit-learn==1.0.2
    - tensorboard==2.6.0
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - tqdm==4.64.1
    - zerorpc==0.6.3